
version: 2

models:
  - name: read_bigquery_data
    description: "Reads data from BigQuery"

  - name: data_pipeline
    description: "Parse Weather data"

  - name: big_query_insert
    description: "Inserts parsed data into BigQuery"
 

