Data_Pipeline:
  target: dev
  outputs:
    dev:
      dataset: weather_data_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt_tutorial_secret
      location: US
      method: service-account
      priority: interactive
      project: hops-20
      threads: 1
      type: bigquery
      # for dbt Python models
      gcs_bucket: maksym_gcs_bucket
      dataproc_region: europe-central2

    prod: # your production environment
      type: bigquery
      method: service-account
      project: hops-20  # name of the project in BigQuery
      dataset: weather_data_demo  # your dataset for production
      threads: 1
      keyfile: /secrets/dbt_tutorial_secret
      timeout_seconds: 300
      priority: interactive
      retries: 1
      # for dbt Python models
      gcs_bucket: maksym_gcs_bucket
      dataproc_region: europe-central2
